# Tesing Twitter Bot

language: python

os:
  - linux

python:
  - 3.6

cache: pip

script:
  - python3 twitter.py robot
  - python3 insta.py


notifications:
  slack:
    rooms:
      - dropnup:x1ZOJDTXefsq1eLGChjXgKhk#general
      - dropnup:x1ZOJDTXefsq1eLGChjXgKhk#dev

before_script:
  - python3 -m pip install -r requirements.txt